services:
  aiunit-tech-radar:
    build:
      context: .
      target: production
    image: aiunit-tech-radar
    container_name: aiunit-tech-radar
    environment:
      APPINSIGHTS_CLOUDROLE: aiunit-tech-radar-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
