environment: production
environmentCode:
name: core-ai-techradar
namespace: core-ai
workstream: core-ai
image: core-ai-techradar

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: core-ai-techradar-config-map

containerSecret:
  name: core-ai-techradar-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000
  azureConnectionString: not-a-real-connection-string
  azureStorageAccount: not-a-real-storage-account
  azureStorageUseConnectionString: false

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

ingress:
  class: nginx
  endpoint: dummy-endpoint
  server: example.com
