environment: production
environmentCode:
name: aiunit-tech-radar
namespace: aiunit-tech
workstream: aiunit-tech
image: aiunit-tech-radar

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: aiunit-tech-radar-config-map

containerSecret:
  name: aiunit-tech-radar-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000
  azureConnectionString: not-a-real-connection-string
  aiUnitTechRadarStorageAccount: not-a-real-storage-account
  azureStorageUseConnectionString: true

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

ingress:
  class: nginx
  endpoint: dummy-endpoint
  server: example.com
