{{- if .Values.aadPodIdentity }}
{{- include "ffc-helm-library.azure-identity-binding" (list . "core-ai-techradar.azure-identity-binding") -}}
{{- end }}
{{- define "core-ai-techradar.azure-identity-binding" -}}
{{- end -}}