{{- include "ffc-helm-library.container-secret" (list . "aiunit-tech-radar.container-secret") -}}
{{- define "aiunit-tech-radar.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
{{- end -}}
